# Options
device: cpu

# Dataset
dataset: /Users/lgl/code/machine_learning/wildlife-segment-anything/data/images/coco
config: /Users/lgl/code/machine_learning/wildlife-segment-anything/data/config/coco.yaml
labels: /Users/lgl/code/machine_learning/wildlife-segment-anything/data/labels/imagenet.txt

# Model
# YOLO v5
yolo: /Users/lgl/code/machine_learning/wildlife-segment-anything/models/yolo/pt/coco.pt
# Segment Anything Model
sam_checkpoint: /Users/lgl/code/machine_learning/wildlife-segment-anything/models/sam/sam_vit_b_01ec64.pth
sam_model_type: vit_b

# Result
save_path: /Users/lgl/code/machine_learning/wildlife-segment-anything/results/results.json
